[env:cardputer]
platform  = espressif32
board     = m5stack-stamps3
framework = arduino

board_build.flash_size          = 8MB
board_build.partitions          = default_8MB.csv
board_upload.flash_size         = 8MB
board_build.arduino.memory_type = qio_opi     ; PSRAM OPI für ESP32-S3

build_flags =
    -DARDUINO_M5STACK_CARDPUTER
    -DBOARD_HAS_PSRAM

lib_deps =
    m5stack/M5Unified @ ^0.2.2
    m5stack/M5GFX    @ ^0.2.4
    tzapu/WiFiManager @ ^2.0.17
