[env:atom-echos3r]
platform  = espressif32
board     = m5stack-atoms3
framework = arduino

lib_deps =
    m5stack/M5Unified
    links2004/WebSockets

monitor_speed = 115200

; PSRAM aktivieren (OPI-Modus für ESP32-S3)
board_build.arduino.memory_type = qio_opi
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
